### ISSUE TITLE
Custom session methods are never called when starting a session. 

### ISSUE THREAD

**Issue by jrots** [windwalker-io/session#1]
AbstractHandler 
registerHandler is never called when doing a normal session ->start() 
only when calling restart(), fork() .. 

so you never can override to a custom sessionhandler.

**Comment by asika32764** [comment]
Thank you for report this issue.

I fixed it in https://github.com/ventoviro/windwalker-session/commit/de415ff6fa5523e24f9ad29db2a9e748f52dfd3a

Please try install `windwalker/session` with `dev-master` to check this issue before new version released.
